### ISSUE TITLE
Compatibility with Objective-C

### ISSUE THREAD

**Issue by ghost** [JeromeTan1997/LocationPicker#1]
Hello Jerome,

Thanks for making such a great framework and sharing it with the world.

I am currently working on an Objective-C project and I was wondering if you could make your framework compatible with Objective-C.

Thank you.

**Comment by zhuorantan** [comment]
Thanks for your feedback, I will address this as soon as possible.

**Comment by zhuorantan** [comment]
Hello,

I've tested `LocationPicker` in Objective-C, there's only one method `addButtons` that is not compatible. I will solve it and release version 1.0.3 several hours later when I'm available. I will inform you in this issue when I'm done. You can integrate it to your project now if this doesn't bother you.

To use `LocationPicker` in Objective-C

``` objective-c
@import LocationPickerViewController;    //If you installed via Cocoapods
@import LocationPicker;    //If you installed in any other way
```

**Comment by zhuorantan** [comment]
@iosmahdi 1.0.3 has been released. `LocationPicker` now is compatible with Objective-C. If you encounter any other issues, please don't hesitate to create an issue or a pull request. Thank you. 😊
