### ISSUE TITLE
FEATURE: History of searched locations

### ISSUE THREAD

**Issue by vongrad** [JeromeTan1997/LocationPicker#21]
First of, I would like to thank you for the amazing work you have done so far!

There is just one thing that I and maybe some other people are still missing, which is a support for history of searched locations.

It could be placed right bellow 'Current location' and have exactly the same behavior.

Let me know what do you think about it.

Thank you in advance!

**Comment by zhuorantan** [comment]
I don't think it's a good idea for a framework to store such data, it's the responsibility of your app. 

`LocationPicker` provides several ways to let your app to do such thing, you should take a look at the demo app which implemented the functionality you are asking with just a few lines of code.

For more information, please read the [Callbacks Section](https://github.com/JeromeTan1997/LocationPicker#callbacks).

**Comment by vongrad** [comment]
Actually, you are right, it should be probably kept out. 

Thank you for the references!
