### ISSUE TITLE
Customize BarButtonItems with addBarButtons func

### ISSUE THREAD

**Issue by guillotemanija** [JeromeTan1997/LocationPicker#23]
Hi, 

I'm trying and failing to customize the "cancel" and "done" bar button items's text.

I have tried doing this but it does not work.
```swift
locationPicker.barButtonItems?.doneButtonItem.title = "newDone"
```
I also tried this with no luck:
```swift
let doneButton = locationPicker.barButtonItems?.doneButtonItem
doneButton?.title = "newDone"
let cancelButton = locationPicker.barButtonItems?.cancelButtonItem
cancelButton?.title = "newCancel"
locationPicker.addBarButtons(doneButtonItem: doneButton, cancelButtonItem: cancelButton, doneButtonOrientation: .right)
```
Could you provide an example on how to do it the right way?
Thank you!

**Comment by zhuorantan** [comment]
You need to create new instances of UIBarButtonItem, and pass them to `addBarButtons`
