### ISSUE TITLE
issue with Carthage

### ISSUE THREAD

**Issue by j-gao** [JeromeTan1997/LocationPicker#3]
I was trying to include this library into my project through Carthage, but the command of 'carthage update' returned the following error message:
(carthage version 0.16.2)

Failed to read file or folder at /private/var/folders/lw/4h75rrkj6c74_htcv9nkk2rw0000gn/T/carthage-archive.Be2knk/__MACOSX/LocationPicker.framework: Error Domain=com.antitypical.Result Code=0 "the DTSDKName key in its plist file is missing" UserInfo={com.antitypical.Result.function=readFailed, NSLocalizedDescription=the DTSDKName key in its plist file is missing, com.antitypical.Result.line=776, com.antitypical.Result.file=/tmp/carthage20160413-39362-hmnet1/Source/CarthageKit/Project.swift}

**Comment by zhuorantan** [comment]
Thanks for your feedback, I will resolve the issue soon.

**Comment by zhuorantan** [comment]
This issue is fixed in version 1.0.4, you can now include this library to your project via Carthage.
