### ISSUE TITLE
Preselection feature

### ISSUE THREAD

**Issue by Ewg777** [JeromeTan1997/LocationPicker#30]
Hey @JeromeTan1997 ,

Is there a way to preselect a location? 
Something like that:
```
let locationPicker = LocationPicker()
locationPicker.pickedLocationItem = myItem
```
or

```
locationPicker.pickedAddress = "Central Park"
```

**Comment by zhuorantan** [comment]
Thanks for your feedback. I will implement this feature soon.

**Comment by zhuorantan** [comment]
Implemented in https://github.com/JeromeTan1997/LocationPicker/releases/tag/3.2

**Comment by Ewg777** [comment]
Amazing! Thanks!

**Comment by RogelioHIT** [comment]
The preselectedIndex is the only way to achieve this?, how can i preselect a coordinate that is not in the tables datasource?
