### ISSUE TITLE
[LocationItem] Fatal Crash in Release Build

### ISSUE THREAD

**Issue by bennnjamin** [JeromeTan1997/LocationPicker#34]
LocationItem initialization seems to crash on iOS 11, perhaps when location or internet is disabled. Here's a stacktrace

0 | LocationPickerViewController | __hidden#211_ line 141specialized LocationItem.init(coder : NSCoder) -> LocationItem
-- | -- | --
1 | LocationPickerViewController | __hidden#211_ line 0_hidden#165_
2 | Foundation | _decodeObjectBinary + 1720
4 | Foundation | +[NSKeyedUnarchiver unarchiveObjectWithData:] + 88
5 | interview | __hidden#5816_ line 22_hidden#5770_
6 | interview | __hidden#5816_ line 0_hidden#5742_
7 | LocationPickerViewController | __hidden#71_ line 340specialized LocationPicker.tableView(UITableView, numberOfRowsInSection : Int) -> Int
8 | LocationPickerViewController | __hidden#71_ line 0_hidden#432_
9 | UIKit | -[UITableView _numberOfRowsInSection:] + 68
40 | UIKit | UIApplicationMain + 236

Line 141 of LocationItem is this one:

```
let addressDictionary = aDecoder.decodeObject(forKey: "addressDictionary") as! [String: AnyObject]
```

I suspect a force downcast would cause the crash but I am not sure what would cause this.

**Comment by zhuorantan** [comment]
Fixed via https://github.com/JeromeTan1997/LocationPicker/commit/af32560131ba6c4f9d7b11dd11f7e3926f894d4f
