### ISSUE TITLE
Offline usage

### ISSUE THREAD

**Issue by v-ken** [JeromeTan1997/LocationPicker#4]
Hey, thanks for sharing this framework. I was hoping to add offline support and was wondering what your thoughts are at the moment?

**Comment by zhuorantan** [comment]
Thanks, It's a good idea. But in that case, location search would be unavailable, there's much to adjusted. I will consider it, or if you are interested, please open a pull request.

**Comment by v-ken** [comment]
You're right. When the user is offline, location will be unavailable. I was thinking of using the text that they have entered into the search field as the `name` in `LocationItem`. `hashValue` might also need to account for this and use the `name` as the hash when coordinates are unavailable. `coordinate` will also need to be changed to an optional type.

What do you think? I'll work on this if you don't see anything majorly wrong with the proposed changes.

**Comment by zhuorantan** [comment]
If the user has to entry the location, it will not be "LocationPicker" anymore. I don't think it's a suitable change to this project. However, if you want something like you described, you can build one based on this project.

**Comment by v-ken** [comment]
The way I've done it also allows user to pick a location if the MKLocalSearch doesn't yield any results. I've created a pull request, let me know if you would like this feature.

**Comment by zhuorantan** [comment]
This feature is added to version 1.1.0

**Comment by v-ken** [comment]
Thanks! Do we need to update `README.md` to include offline behaviour? `LocationItem.coordinate` may be invalid if user is offline. Users may need to check `CLLocationCoordinate2DIsValid(coordinate)`.

**Comment by zhuorantan** [comment]
I think it would be better to modify `LocationItem`, I will work on that.

**Comment by zhuorantan** [comment]
I made `coordinate` in `LocationItem` an optional property and added a new init method, how do you think about it? 60e5e9786d61ad5898b8107d13ac68df426fc3f1

**Comment by v-ken** [comment]
Looks good! Thanks!
