### ISSUE TITLE
Incompatible with Swift 5

### ISSUE THREAD

**Issue by Rebecca-Qian** [JeromeTan1997/LocationPicker#42]
I am getting a compiler error using Swift 5:

`{path to project}/Pods/LocationPickerViewController/LocationPicker/LocationItem.swift:122:24: value of type 'AnyObject' has no member 'hashValue'`

This is the function causing problems:

`    open override func isEqual(_ object: Any?) -> Bool {
        guard let object = object else { return false }
        return (object as! NSObject).hashValue == hashValue
    }`

Since this class subclasses from NSObject, can we use the default NSObject isEqual definition instead? Thanks for looking into this.

**Comment by edwardmp** [comment]
I submitted a PR to fix this. I'm not 100% sure that fix is correct, but it seems so.

**Comment by uknowmeright** [comment]
for swift 5 support pull from:

pod 'LocationPickerViewController', :git => 'https://github.com/zhuorantan/LocationPicker.git', :branch => 'master'
