### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by iMarwan-k** [JeromeTan1997/LocationPicker#7]
Hello, I tried to run the demo but seems like it miss locationPicker.framework file. could you please fix it

thank you

**Comment by otymartin** [comment]
Having the same problem

**Comment by zhuorantan** [comment]
Sorry for the problem, I will fix it soon. For now, you can fix it locally by:
1. Delete the **LocationPicker.framework** in **LocationPickerDemo.xcodeproj**
2. Build **LocationPicker**
3. Drag the **LocationPicker.framework** in the **Products** group of **LocationPicker** to **Embedded Binaries** of **LocationPickerDemo.xcodeproj**

**Comment by zhuorantan** [comment]
This issue has been fixed in 1.1.2 release.
