### ISSUE TITLE
how to control Done and Cancel 

### ISSUE THREAD

**Issue by iMarwan-k** [JeromeTan1997/LocationPicker#8]
Hi, I tried to find out how to control this 2 buttons but I could not find out how to do it

can you  please give me an example to how to deal with it

thank you

**Comment by zhuorantan** [comment]
What do you mean by "control"? If you mean to customize these two buttons, please refer to https://github.com/JeromeTan1997/LocationPicker#methods. Or if you want to access the properties or methods of these two buttons, there is a `barButtonItems` property in `LocationPicker` class.
